"""Verify the requested native menu interactions, including intermediate frames."""
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtTest import QTest

from dashboard_nav import DESTINATIONS


def run_navigation(app, w, folder, check):
    from workspace_ui import save_perspective, restore_perspective, toggle_focus
    nav = w.navigation
    def hover(row):
        # QWidget-level QTest.mouseMove does not deliver Enter reliably under
        # Windows display scaling; deliver Qt's actual hover entry event.
        point = QtCore.QPointF(row.rect().center())
        event = QtGui.QEnterEvent(point, point, QtCore.QPointF(row.mapToGlobal(point.toPoint())))
        QtWidgets.QApplication.sendEvent(row, event)
        app.processEvents()
    nav.mode_selector.setCurrentText("顶部导航")
    nav.navigate("scope")
    w.resize(1550, 940)
    QTest.qWait(380)
    check("dashboard_defaults_to_native_top_navigation", nav.top_toolbar.isVisible() and not nav.side_toolbar.isVisible())
    check("navigation_preserves_large_waveform", w.plot.width() > .7 * w.width() and w.plot.height() > .72 * w.height())
    hover(nav.headings["实验"])
    QTest.qWait(280)
    check("hover_opens_full_width_menu", nav.panel.isVisible() and nav.panel.width() == w.width() - 24 and nav.panel.group == "实验")
    height = nav.panel.height()
    panel = nav.panel
    hover(nav.headings["工作台"])
    app.processEvents()
    check("hover_switch_retains_open_panel_and_height", nav.panel is panel and nav.panel.isVisible() and nav.panel.height() == height and nav.panel.group == "工作台")
    w.grab().save(str(folder / "dashboard-top-menu.png"))
    QTest.mouseClick(nav.panel.rows["tuning"], QtCore.Qt.MouseButton.LeftButton)
    QTest.qWait(380)
    check("mega_menu_routes_to_live_tuning", not nav.panel.isVisible() and w.layout_name == "调参" and nav.current == "tuning")
    nav.set_current("comparison", False)
    start = QtCore.QRectF(nav.header.highlight)
    nav.set_current("scope")
    QTest.qWait(110)
    middle = QtCore.QRectF(nav.header.highlight)
    check("rounded_highlight_moves_and_resizes_in_flight", middle != start and middle != nav.header.row_rect(nav.headings["工作台"]) and middle.width() != start.width())
    check("highlight_uses_small_rebound", nav.header.motion.easingCurve().type() == QtCore.QEasingCurve.Type.OutBack and nav.header.motion.easingCurve().overshoot() < 1)
    QTest.qWait(300)
    check("highlight_finishes_on_target_geometry", nav.header.highlight == nav.header.row_rect(nav.headings["工作台"]))
    nav.mode_selector.setCurrentText("侧栏导航")
    QTest.qWait(380)
    check("sidebar_navigation_switch_is_real", nav.side_toolbar.isVisible() and all(not row.isVisible() for row in nav.headings.values()))
    side = nav.sidebar
    QTest.mouseClick(side.headers["实验"], QtCore.Qt.MouseButton.LeftButton)
    QTest.qWait(120)
    section = side.sections["实验"]
    rows = list(section.rows.values())
    check("submenu_children_reveal_with_stagger", 0 < section.amount < 1 and rows[0].reveal > rows[1].reveal)
    check("submenu_arrow_rotates_in_flight", 0 < side.headers["实验"].angle < 90)
    check("only_one_branch_is_open_during_animation", side.sections["工作台"].height() == 0 and sum(s.height() > 0 for s in side.sections.values()) == 1)
    QTest.qWait(240)
    check("submenu_arrow_finishes_at_90_degrees", side.headers["实验"].angle == 90 and section.height() == section.full_height)
    QTest.mouseClick(side.headers["分析"], QtCore.Qt.MouseButton.LeftButton)
    app.processEvents()
    check("opening_next_group_closes_previous_immediately", section.height() == 0 and side.open_group == "分析")
    QTest.qWait(380)
    QTest.mouseClick(side.sections["分析"].rows["rule"], QtCore.Qt.MouseButton.LeftButton)
    QTest.qWait(750)
    check("sidebar_leaf_routes_to_rule_panel", nav.current == "rule" and w.analysis_tabs.currentIndex() == 0 and w.analysis_dock.isVisible())
    check("sidebar_highlight_matches_leaf_size_and_position", side.highlight == side.row_rect(side.sections["分析"].rows["rule"]))
    w.grab().save(str(folder / "dashboard-sidebar.png"))
    QTest.mouseClick(side.headers["分析"], QtCore.Qt.MouseButton.LeftButton)
    QTest.qWait(260)
    check("clicking_open_group_collapses_it", side.open_group is None and all(s.height() == 0 for s in side.sections.values()))
    nav.mode_selector.setCurrentText("顶部导航")
    nav.navigate("scope")
    QTest.qWait(350)
    w.timer.start()
    before = len(w.experiment.samples)
    QTest.keyClick(w, QtCore.Qt.Key.Key_K, QtCore.Qt.KeyboardModifier.ControlModifier)
    QTest.qWait(100)
    palette = nav.palette
    check("ctrl_k_opens_centered_command_palette", palette.isVisible() and palette.input.hasFocus() and abs(palette.card.geometry().center().x() - w.rect().center().x()) <= 1)
    check("palette_blurs_snapshot_without_changing_live_widgets", not palette.background.isNull() and w.plot.graphicsEffect() is None)
    background = palette.background.toImage()
    check("high_dpi_blur_covers_entire_background", background.pixelColor(background.width() - 30, background.height() - 30).alpha() > 200 and palette.background.devicePixelRatio() == w.devicePixelRatio())
    check("command_palette_lists_real_destinations", palette.results.count() == len(DESTINATIONS))
    QTest.keyClick(palette.input, QtCore.Qt.Key.Key_Down)
    check("command_down_selects_next_result", palette.results.currentRow() == 1)
    QTest.keyClick(palette.input, QtCore.Qt.Key.Key_Up)
    check("command_up_selects_previous_result", palette.results.currentRow() == 0)
    QTest.keyClicks(palette.input, "PID")
    check("command_filters_on_each_keystroke", {palette.results.item(i).text() for i in range(palette.results.count())} == {"PID 调参", "工程源码"} and palette.results.item(0).text() == "PID 调参")
    check("command_highlights_matching_text_and_escapes_html", "text-decoration:underline" in palette.delegate.marked("PID 调参", "#529bd5") and "&lt;" in palette.delegate.marked("<PID>", "#529bd5"))
    QTest.qWait(250)
    check("acquisition_continues_under_command_overlay", len(w.experiment.samples) > before)
    w.grab().save(str(folder / "dashboard-command.png"))
    actual = w.params.kp
    QTest.keyClick(palette.input, QtCore.Qt.Key.Key_Return)
    QTest.qWait(400)
    check("command_enter_navigates_without_parameter_write", not palette.isVisible() and w.layout_name == "调参" and w.params.kp == actual)
    QTest.keyClick(w, QtCore.Qt.Key.Key_K, QtCore.Qt.KeyboardModifier.ControlModifier)
    QTest.qWait(80)
    palette.input.setText("no-such-page-123456")
    check("command_handles_empty_matches", palette.results.count() == 0 and palette.empty.isVisible())
    QTest.keyClick(palette.input, QtCore.Qt.Key.Key_Return)
    check("empty_command_enter_does_not_navigate", palette.isVisible() and nav.current == "tuning")
    QTest.keyClick(palette.input, QtCore.Qt.Key.Key_Escape)
    check("escape_dismisses_command_overlay", not palette.isVisible())
    nav.mode_selector.setCurrentText("侧栏导航")
    save_perspective(w)
    nav.mode_selector.setCurrentText("顶部导航")
    restore_perspective(w)
    check("saved_workspace_restores_navigation_mode", nav.mode == "侧栏导航" and nav.side_toolbar.isVisible())
    toggle_focus(w)
    app.processEvents()
    check("f11_hides_both_navigation_surfaces", not nav.top_toolbar.isVisible() and not nav.side_toolbar.isVisible() and w.plot.width() > .95 * w.width())
    toggle_focus(w)
    app.processEvents()
    check("f11_restores_sidebar_navigation", nav.top_toolbar.isVisible() and nav.side_toolbar.isVisible())
    nav.mode_selector.setCurrentText("顶部导航")
    nav.navigate("scope")
    w.theme_selector.setCurrentText("浅色工作台")
    QTest.qWait(380)
    nav.hover_group("工作台")
    QTest.qWait(280)
    w.grab().save(str(folder / "dashboard-light-menu.png"))
    nav.close_panel()
    w.theme_selector.setCurrentText("深色仪器")
    w.resize(1100, 720)
    QTest.qWait(100)
    check("compact_navigation_does_not_clip_header", nav.mode_selector.isVisible() and nav.header.width() <= w.width() and w.minimumSizeHint().width() <= 1100)
    check("compact_top_navigation_keeps_plot_useful", w.plot.height() > 480 and w.plot.width() > 760)
    w.grab().save(str(folder / "dashboard-compact.png"))
    w.resize(1550, 940)
    nav.navigate("tuning")
    QTest.qWait(380)
    w.grab().save(str(folder / "dashboard-tuning-final.png"))
